### ISSUE TITLE
Judgement: Can we change our votes after voting?

### ISSUE THREAD

**Issue by piersb** [audiodude/tiny-nomic#20]
https://github.com/audiodude/tiny-nomic/pull/19 raised an interesting question. 

@selfsame said "voting no to get 10 dissent points :)", and then afterwards voted 👍.

As it turns out, that first comment wasn't actually a vote per https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/117_Github-repository.md, so it's not relevant right now.

But if it had been a real vote: is a vote, once placed in a comment, unchangeable?

@Cardboard, I believe you're judging.

**Comment by audiodude** [comment]
Actually, it was initially a vote, with a proper :-1:. However it was later edited.

**Comment by audiodude** [comment]
Ping.

**Comment by william42** [comment]
I think we might actually need judgement on two points: can you change your vote, and can/should you edit your posts?

Edit(@audiodude): Remove email gunk from message

**Comment by audiodude** [comment]
Voting is tricky because the rules talk about each player having one vote, players being required to vote, and a 👍  or 👎  counting as a vote.

As far as editing posts in general, I think it falls under https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/116_Not-otherwise-prohibited.md, but you are free to invoke judgement on that point as well. I feel like it should be in its own Issue though, for better bookkeeping.

**Comment by william42** [comment]
I suspect that along 116 lines that if editing is allowed, changing your vote (until the vote is closed) is allowed; the question then becomes what happens if you want to change your vote but forget to edit.

**Comment by audiodude** [comment]
Actually that was my point, the rules *do* talk about the process of voting, so it wouldn't be covered by 116. For example: https://github.com/audiodude/tiny-nomic/blob/master/mutable_rules/207_Votes-per-player.md could be read as "Each player always has exactly one vote, so once it is cast it can't be retracted" because if you can change your vote, aren't you technically voting twice (even though only one counts).

Also:
https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/117_Github-repository.md
> Players vote on Pull Requests/proposals by putting either "+1" or "-1" as a comment on the Pull Request, or by using the proper 👍 or 👎 emoji on the Pull Request comment.

So once you've done that, you've voted. In combination with the rule above, it seems like you can't change your vote.

**Comment by william42** [comment]
But that doesn't say "Each player has only one vote, which cannot be changed after being cast."

Edit(@audiodude): remove email gunk.

**Comment by audiodude** [comment]
If each player has one vote, and putting 👍  or 👎  is voting, then you can't change your vote because you'd be required to put 👍  or 👎  a second time, which could be considered another vote.

Also if you read https://github.com/audiodude/tiny-nomic/blob/master/immutable_rules/111_Time-for-debate.md 

> before the vote
> also decides the time to end debate and vote.

This seems to imply that "the vote" is a single, one-time event. Picture playing this game around a table. You would either all raise your hands to vote or maybe write it on a paper, but either way it would happen all at once. How would you change your vote then?

The ambiguity comes from the fact that our votes are temporally elongated.

**Comment by Cardboard** [comment]
Following this discussion, I seem to agree most strongly with audiodude, where voters are unable to change their vote (via editing or otherwise). If one interprets "one vote" (vote=noun) as implying one gets to put forth either a :+1: or :-1:, then I think editing would be permitted, but reading "one vote" (vote=verb) as meaning "able to engage in the act of voting, once", then audiodude's reasoning makes sense. I think in the interest of keeping the voting consistent and not needing to ever recount votes due to vote-switching (as well as being most similar to paper-pen/hand-raising voting), I'm going to have to agree with audiodude's interpretation of the rules --- Players can engage in the act of voting once, putting forth either a :+1: or :-1:, and cannot change their decision at a later time.

**Comment by audiodude** [comment]
Thanks @Cardboard !
