### ISSUE TITLE
Judgement: Did 308 pass with abstain votes?

### ISSUE THREAD

**Issue by audiodude** [audiodude/tiny-nomic#28]
@fonorobert believes that proposal 308 (as outlined in #26) passed. I believe it failed because we still require unanimous votes and abstain votes aren't "yes" votes.

@selfsame I'm pretty sure you are the judge.

**Comment by selfsame** [comment]
Traditionally (see Robert's Rules of order) an abstained vote is an oxymoron, as it's a refusal to vote, and has no weight in the ratio of yes to no.  The exception to this is if the vote requires a majority or unanimity of members present.

Since nothing in our rules points towards a unanimity of members present, I judge that abstention is participation but has no value in itself that can be tallied, and as so proposal 308 has successfully passed.
